name: Convert Markdonw to JSON
author: Benjamin Wuethrich
description: Produces a JSON syntax tree for Markdown input

branding:
  color: orange
  icon: filter

inputs:
  markdown-string:
    description: The Markdown to be converted
    required: true
  token:
    description: Token to access the repository
    required: true

outputs:
  json:
    description: A JSON syntax tree for the input Markdown
    value: ${{ steps.convert.outputs.json }}

runs:
  using: composite
  steps:
    - name: Install remark-cli
      shell: bash
      run: |
        npm install remark-cli

    - name: Convert Markdown to JSON
      id: convert
      env:
        markdown: ${{ inputs.markdown-string }}
        GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash
      run: |
        "$GITHUB_ACTION_PATH/md2json" "$markdown"
