name: Convert Markdonw to JSON
author: Benjamin Wuethrich
description: Produces a JSON syntax tree for Markdown input

branding:
  color: orange
  icon: filter

inputs:
  markdown:
    description: The Markdown to be converted
    required: true

outputs:
  json:
    description: A JSON syntax tree for the input Markdown
    value: ${{ steps.convert.outputs.json }}

runs:
  using: composite
  steps:
    - name: Install remark-cli
      shell: bash
      run: |
        npm install --global remark-cli@11.0.0

    - name: Convert Markdown to JSON
      id: convert
      env:
        markdown: ${{ inputs.markdown }}
      shell: bash
      run: |
        "$GITHUB_ACTION_PATH/md2json" "$markdown"
