name: Name of action
author: Benjamin Wuethrich
description: Description of action

branding:
  color: white
  icon: cpu

inputs:
  required-input:
    description: Description of required input
    required: true
  optional-input:
    description: Description of optional input
    required: false
    default: <value>

outputs:
  output:
    description: Description of output
    value: ${{ steps.getbranchname.outputs.name }}
  date:
    description: The date portion of the branch name
    value: ${{ steps.stepid.outputs.output }}

runs:
  using: composite
  steps:
    - name: Step name
      id: stepid
      env:
        required: ${{ inputs.required-input }}
        optional: ${{ inputs.optional-input }}
      shell: bash
      run: |
        echo "Running the script..." >&2
        "$GITHUB_ACTION_PATH/script" "$required" "$optional"
