#!/usr/bin/env bash

set -o errexit

markdown=$1

echo "::group::Markdown input"
printf '%s\n' "$markdown"
echo "::endgroup::"

json=$(remark --tree-out --frail <<< "$markdown")

echo "::group::JSON output"
printf '%s\n' "$json"
echo "::endgroup::"

echo "json=$(jq --raw-input --slurp . <<< "$json")" >> "$GITHUB_OUTPUT"
